# supabase/config.toml

# Define as configurações para a função específica 'update-prospect-stats'
[functions.update-prospect-stats]
# Aponta para o mapa de importação. O caminho é relativo à raiz do projeto.
# O caminho deve ser relativo à pasta 'supabase', onde este config.toml está.
import_map = "import_map.json"

# Configuration for the Stripe webhook function
[functions.webhook-stripe]
verify_jwt = false
[functions.calculate-trends]
enabled = true
verify_jwt = true
import_map = "./functions/calculate-trends/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/calculate-trends/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/calculate-trends/*.html" ]
